name: Build posts

on:
  push:
    paths:
      - "posts/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm install

    - name: Build posts
      run: yarn build

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<email@example.com>"
        git add -A
        git commit -m "Build posts" || echo "No changes"
        git push
