name: Build posts

on:
  push:
    paths:
      - "posts/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd build
        yarn
        yarn build
        cd ..

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<email@example.com>"
        git add .
        git commit -m "Build posts" || echo "No changes to commit"
        git push
